Repository Melon-Shake/API, pull requests merged in 2023-09, with the labels that each got.

#22 v0.1.0 국내 5개 차트 통합 기능
  .gitignore
  MelonApi.py
  __pycache__/MelonApi.cpython-39.pyc
  test/api_requessts_melon.py
  test/getchart.py
Labels: task

#39 v0.1.0/js-musixmatch 가사 크롤링
  Pipfile
  Pipfile.lock
  getTrackLyrics.py
Labels: DONE

#40 v0.1.0/register api
  register_keyword_api.py
Labels: DONE

#44 v0.1.0 비적재 spotify search api
  .gitignore
  __pycache__/module.cpython-38.pyc
  __pycache__/module.cpython-39.pyc
  __pycache__/sp_search.cpython-39.pyc
  getTokenByRefreshToken.py
  inputAlbumDataToDB.py
  inputArtistDataToDB.py
  inputTrackDataToDB.py
  junsungcode.py
  module.py
  sp_getSearchResult.py
  sp_search.py
Labels: task

#76 v0.2.0/presto/release-test EC2 웹 호스팅 확인 작업
  Dockerfile
  model/spotify_client.py
  model/spotify_token.py
  requirements.txt
  src/TotalApi.py
  src/getTokenByRefreshToken.py
  src/inputAlbumDataToDB.py
  src/inputArtistDataToDB.py
  src/inputTrackDataToDB.py
  src/lyric.py
  src/register_client.py
  src/sp_artist.py
  src/sp_track.py
  src/test_artist.py
  src/test_getSearchResult.py
  src/update_token.py
Labels: DONE

#77 V0.2.0/presto/release test main EC2 웹 호스팅 확인 작업
  Dockerfile
  README.md
  model/spotify_client.py
  model/spotify_token.py
  requirements.txt
  src/TotalApi.py
  src/getTokenByRefreshToken.py
  src/inputAlbumDataToDB.py
  src/inputArtistDataToDB.py
  src/inputTrackDataToDB.py
  src/lyric.py
  src/register_client.py
  src/sp_artist.py
  src/sp_track.py
  src/test_artist.py
  src/test_getSearchResult.py
  src/update_token.py
Labels: DONE

#89 v0.2.0/sophie/chart_genie hotfix
  src/load_chart_genie.py
Labels: DONE

#63 v0.2.0/ssg/youtubechart start
  genie.py
  inputAudiofeaturesToDB.py
  model/ytmusic.py
  requirements.txt
  sample2.py
  src/test_getSearchResult.py
  src/youtube_chart_jshy.py
  yt_craw_function0.py
Labels: task

#100 V0.2.0/bkson/각 사이트별 차트 정규화하여 서치로 제공
  .gitignore
  src/TotalApi.py
  src/data.csv
  src/data1.csv
  src/intergrated_chart.py
  src/load_chart_bugs.py
  src/load_chart_flo.py
  src/load_chart_genie.py
  src/load_chart_melon.py
  src/load_chart_vibe.py
Labels: 차트

#103 V0.2.0/sophie/load spotify
  model/chart_flo.py
  model/chart_melon.py
  model/spotify_albums.py
  model/spotify_artists.py
  model/spotify_search.py
  model/spotify_tracks.py
  sql/spotify_albums.sql
  sql/spotify_tracks.sql
  src/search_spotify.py
Labels: 검색

#104 V0.2.0/bkson/스포티파이 서치로 각 차트 서빙
  README.md
  model/chart_bugs.py
  model/chart_flo.py
  src/TotalApi.py
  src/bugs_load.py
  src/data.csv
  src/data1.csv
  src/load_chart_bugs.py
  src/load_chart_flo.py
  src/load_chart_genie.py
  src/load_chart_melon.py
  src/load_chart_vibe.py
  src/load_flo.py
Labels: 차트

#113 V0.2.0/bkson/intergrated chart hotfix
  src/load_chart_bugs.py
Labels: 차트

#111 V0.2.0/sophie/bring lyric
  sql/lyrics_temp.sql
Labels: 검색

#112 v0.2.0/sophie/bring_audiofeatures
  data/detail.json
  data/search.json
  model/audio_features.py
  model/metadata.py
  model/spotify_search.py
  sql/audio_features.sql
  sql/lyrics_temp.sql
  sql/spotify_audio_features.sql
  src/get_token.py
  src/lyric.py
  src/lyrics_analyze.py
  src/search_spotify.py
  src/track_analyze.py
Labels: 검색

#117 V0.2.0/sophie/modify charts column
  model/chart_bugs.py
  model/chart_flo.py
  model/chart_genie.py
  model/chart_melon.py
  model/chart_vibe.py
  sql/chart_bugs.sql
  sql/chart_flo.sql
  sql/chart_genie.sql
  sql/chart_melon.sql
  sql/chart_vibe.sql
  src/intergrated_chart.py
  src/load_chart_bugs.py
  src/load_chart_genie.py
  src/load_chart_melon.py
  src/load_chart_vibe.py
Labels: 차트

#122 V0.2.0/sophie/add api
  data/detail.json
  data/search.json
  src/function.py
  src/lyrics_analyze_1.py
  src/lyrics_analyze_2.py
Labels: 검색

#115 V0.3.0/jun/dummy data 사용자 행동 더미 데이터 확보 및 적재
  .gitignore
  model/bugs_db.py
  requirements.txt
  src/daily_search_ranking.py
  src/inputTrackDataToDB.py
  src/intergrated_chart.py
  src/load_dummy.py
  src/user_search_track.py
Labels: 분석

#128 V0.3.0/ssg/update chart
  .gitignore
  model/chart_bugs.py
  model/chart_flo.py
  model/chart_genie.py
  model/chart_melon.py
  model/chart_vibe.py
  src/TotalApi.py
  src/integrated_chart.py
  src/load_chart_bugs.py
  src/load_chart_flo.py
  src/load_chart_genie.py
  src/load_chart_melon.py
  src/load_chart_vibe.py
Labels: 차트

#118 0.3.0/jhy/add lyrics craw
  model/__init__.py
Labels: 검색

#131 V0.3.0/jun/playlist
  .gitignore
  model/chart_flo.py
  model/jun_model.py
  requirements.txt
  src/TotalApi.py
  src/inputTrackDataToDB.py
  src/load_dummy.py
  src/lyrics_analyze_1.py
  src/lyrics_analyze_2.py
  src/make_playlist.py
  src/search_spotify.py
  src/update_user_feature.py
Labels: 분석

#124 V0.3.0/jhy/user analyze and recommand
  model/chart_flo.py
  sql/lyrics_temp.sql
  src/TotalApi.py
  src/api_sophie.py
  src/full_analyze.py
  src/function.py
  src/load_chart_bugs.py
  src/load_chart_vibe.py
  src/lyric.py
  src/lyrics_analyze_1.py
  src/lyrics_analyze_2.py
  src/search_spotify.py
  src/show_analyze.py
  src/user_analyze.py
Labels: 분석

#139 V0.3.0/sophie/modify api
  src/full_analyze.py
  src/function.py
  src/integrated_chart.py
  src/lyric.py
  src/search_spotify.py
Labels: 검색, 차트

#126 V0.3.0/dev
  .gitignore
  model/__init__.py
  model/chart_bugs.py
  model/chart_flo.py
  model/chart_genie.py
  model/chart_melon.py
  model/chart_vibe.py
  model/database.py
  model/jun_model.py
  model/metadata.py
  model/spotify_client.py
  model/spotify_search.py
  model/ytmusic.py
  requirements.txt
  sql/chart_bugs.sql
  sql/chart_flo.sql
  sql/chart_genie.sql
  sql/chart_melon.sql
  sql/chart_vibe.sql
  src/TotalApi.py
  src/api_sophie.py
  src/daily_search_ranking.py
  src/full_analyze.py
  src/function.py
  src/getTokenByRefreshToken.py
  src/get_keyword.py
  src/get_token.py
  src/google_lyrics.py
  src/inputAlbumDataToDB.py
  src/inputArtistDataToDB.py
  src/inputTrackDataToDB.py
  src/integrated_chart.py
  src/load_chart_bugs.py
  src/load_chart_flo.py
  src/load_chart_genie.py
  src/load_chart_melon.py
  src/load_chart_vibe.py
  src/load_dummy.py
  src/lyric.py
  src/lyrics_analyze.py
  src/lyrics_analyze_2.py
  src/make_playlist.py
  src/ml_playlist.py
  src/register_client.py
  src/search_spotify.py
  src/show_analyze.py
  src/sp_artist.py
  src/sp_track.py
  src/test_artist.py
  src/test_getSearchResult.py
  src/track_analyze.py
  src/update_token.py
  src/update_user_feature.py
  src/user_analyze.py
  src/user_search_track.py
  src/youtube_chart_jshy.py
Labels: release
